name: darts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  drift: ^2.34.1
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  meta: ^1.18.0
  path: ^1.9.1
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  share_plus: ^13.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.3
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
